### ISSUE TITLE
有问题？？？

### ISSUE THREAD

**Issue by zsbox** [chokcoco/webpack_demo#1]
首先 npm install 提示
![image](https://user-images.githubusercontent.com/20392882/29442633-6f191be4-8405-11e7-90c3-16c13f969376.png)
然后npm run dev
![image](https://user-images.githubusercontent.com/20392882/29442664-9cf629b2-8405-11e7-8f61-58065b61aca8.png)
然后浏览器打开是这样 
![image](https://user-images.githubusercontent.com/20392882/29442616-4f6364da-8405-11e7-8cec-a9ab6137228e.png)
是否本人有哪里操作有问题呢

**Comment by chokcoco** [comment]
@zsbox 
没问题，这不是已经打开 127.0.0.1:8000 了，这是启动后默认打开的页面。可以点 src -> html -> index.html

然后
![image](https://user-images.githubusercontent.com/8554143/29443498-09ecc27e-840b-11e7-8b97-31ba78732bf2.png)
这一块是配置了 eslint 规则，可以在根目录下 `.eslintrc.json` 进行规则修改，具体规则参阅 http://eslint.cn/docs/rules/

这个是我自己比较喜欢的一个脚手架，可能不适合每个人，可以根据自己的喜欢修改。

**Comment by zsbox** [comment]
我再试试 不行再问你  快被webpack弄炸了
